apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebapp-ENVIRONMENT-BUILD_NUMBER
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: javawebapp
        version: "BUILD_NUMBER"
    spec:
      containers:
      - name: ivak/myimage:latest
        image: IMAGE
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
