pipeline:
  identifier: Build_java_web_app_docker_1698733216565
  name: Build java-web-app-docker
  orgIdentifier: default
  projectIdentifier: nginx
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1698733181227
        repoName: java-web-app-docker
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: javaweb_app
                    repo: mywebapp
                    tags:
                      - mywebapp
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
